import {
  ThuVien,
  KhamPha,
  Zingchart,
  Radio,
  Album,
  Bxh,
  Chude,
  Ganday,
  Top100,
  Playlist,
  YeuThich,
} from "~/assets/index";
import Home from "~/page/Home/Home";
import Favourite from "~/page/Favourite/index";

export const links = [
  {
    name: "Thư Viện",
    path: "/thu-vien",
    link: true,
    icon: <ThuVien className="w-6 h-6" />,
    component: Home,
    layout: 1,
  },
  {
    name: "Khám Phá",
    path: "/",
    link: true,
    icon: <KhamPha className="w-6 h-6" />,
    component: Home,
    layout: 1,
  },
  {
    name: "Zingchart",
    path: "/zing-chart",
    link: true,
    icon: <Zingchart className="w-6 h-6" />,
    component: Favourite,
    layout: 1,
  },
  {
    name: "Radio",
    path: "/Radio",
    link: true,
    icon: <Radio className="w-6 h-6" />,
    component: Home,
    layout: 1,
  },
  {
    name: "BXH Nhạc Mới",
    path: "/moi-phat-hanh",
    link: true,
    icon: <Bxh className="w-6 h-6" />,
    component: Home,
    layout: 2,
  },
  {
    name: "Chủ Đề",
    path: "/chu-de",
    link: true,
    icon: <Chude className="w-6 h-6" />,
    component: Home,
    layout: 2,
  },
  {
    name: "Top 100",
    path: "/top100",
    link: true,
    icon: <Top100 className="w-6 h-6" />,
    component: Home,
    layout: 2,
  },
  {
    name: "Nghe Gần Đây",
    path: "/nghe-gan-day",
    link: false,
    icon: <Ganday className="w-6 h-6" />,
    component: Home,
    layout: 3,
  },
  {
    name: "Bài Hát Yêu Thích",
    path: "/bai-hat-yeu-thich",
    link: true,
    icon: <YeuThich className="w-6 h-6" />,
    component: Home,
    layout: 3,
  },
  {
    name: "Album",
    path: "/album",
    link: true,
    icon: <Album className="w-6 h-6" />,
    component: Home,
    layout: 3,
  },
  {
    name: "Playlist",
    path: "/Play-list",
    link: true,
    icon: <Playlist className="w-6 h-6" />,
    component: Home,
    layout: 3,
  },
];
